# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

# Pre-install packages for the ubuntu distribution
cache:
  apt: true

addons:
  apt:
    packages:
      - libatlas3gf-base
      - libatlas-dev
      - python-scipy
      - python-matplotlib
      - gcc-msp430
      - tshark

before_install:
  - "git clone --recursive git://github.com/contiki-os/contiki"

script:
  - "ipython nbconvert --to=python demo.ipynb"
  - python demo.py

cache: pip

notifications:
  email: false
